# Generated by Django 3.1.7 on 2021-04-18 09:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('thirdplace', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beverage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('isCore', models.BinaryField(default=False)),
                ('iced', models.BinaryField()),
                ('type', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Instruction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instructionDetail', models.CharField(max_length=50)),
                ('bevID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thirdplace.beverage')),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingName', models.CharField(max_length=5)),
                ('quantity', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('bevID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thirdplace.beverage')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('comment', models.TextField()),
                ('beverageID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thirdplace.beverage')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CustomBeverage',
            fields=[
                ('beverage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='thirdplace.beverage')),
                ('createdBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('thirdplace.beverage',),
        ),
    ]
